# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedSquareRoute' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedSquareRoute
  pod 'GoogleMaps'
  pod 'GooglePlaces'


  target 'RedSquareRouteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
